export const CONSTANTS = {
  CODELISTS: {
    ADDRESSTYPE: 'ADDRESSTYPE',
    PLANCATEGORY: 'PLANCATEGORY',
    PLANTYPE: 'PLANTYPE',
    PRODUCTCATEGORY: 'PRODUCTCATEGORY',
    PRODUCTTYPE: 'PRODUCTTYPE',
    USERTYPE: 'USERTYPE',
    SEARCHBYUSER:'SEARCHUSERBY'
  },
  SERACHBYCATEGORY: {
    DRINK: 'DRINK',
    DESERT: 'DESERT',
    MAIN: 'MAIN'
  },
  SERACHBYTYPE: {
    MEAL: 'MEAL',
    ADDON: 'ADDON'
  }
}
